openapi: 3.0.0
info:
  title: Word Cloud
  version: 0.1.0
  description: "## This is API server that provides word cloud image using image and text. \n This server use python library from [word_cloud](https://github.com/amueller/word_cloud) opensource project to genereate word cloud. \n### Supported Language:\n- English \n- coming soon..\n\n ### Supported Word Cloud:\n- Image color\n- Mask color "
  contact:
    name: API Support (Feature Request, Report Issue)
    url: 'https://github.com/gkswjdzz/word_cloud'   
paths:
  /image_color:
    post:
      tags:
        - Word Cloud
      summary: Color a word-cloud based on source image.
      description: "[Sample Photo Download Link](https://raw.githubusercontent.com/amueller/word_cloud/master/examples/alice_color.png)\n[Sample Text Download Link](https://raw.githubusercontent.com/amueller/word_cloud/master/examples/alice.txt)"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                lang:
                  type: string
                  default: en_ewt_0.2.0
                  enum:
                  - en_ewt_0.2.0
                image:
                  type: string
                  format: binary
                text:
                  type: string
                  format: binary
                font_size:
                  type: integer
                  description: 'range : 1 ~ 100'
                  minimum: 1
                  maximum: 100
                  default: 40
                thing:
                  type: string
                  default: person
                  enum:
                  - person
                  - bicycle
                  - car
                  - motorcycle
                  - airplane
                  - bus
                  - train
                  - truck
                  - boat
                  - traffic light
                  - fire hydrant
                  - street sign
                  - stop sign
                  - parking meter
                  - bench
                  - bird
                  - cat
                  - dog
                  - horse
                  - sheep
                  - cow
                  - elephant
                  - bear
                  - zebra
                  - giraffe
                  - hat
                  - backpack
                  - umbrella
                  - shoe
                  - eye
                  - handbag
                  - tie
                  - suitcase
                  - frisbee
                  - skis
                  - snowboard
                  - sports ball
                  - kite
                  - baseball
                  - baseball glove
                  - skateboard
                  - surfboard
                  - tennis racket
                  - bottle
                  - plate
                  - wine glass
                  - cup
                  - fork
                  - knife
                  - spoon
                  - bowl
                  - banana
                  - apple
                  - sandwich
                  - orange
                  - broccoli
                  - carrot
                  - hot dog
                  - pizza
                  - donut
                  - cake
                  - chair
                  - couch
                  - potted
                  - bed
                  - mirror
                  - dining table
                  - window
                  - desk
                  - toilet
                  - door
                  - tv
                  - laptop
                  - mouse
                  - remote
                  - keyboard
                  - cell phone
                  - microwave
                  - oven
                  - toaster
                  - sink
                  - refrigerator
                  - blender
                  - book
                  - clock
                  - vase
                  - scissors
                  - teddy bear
                  - hair drier
                  - toothbrush
                  - hair brush
      responses:
        '200':
          description: Result image.
          content:
            image/*:
              schema:
                type: string
                format: binary
        '400':
          description: Bad request
  /random_color:
    post:
      tags:
        - Word Cloud
      summary: Color a word-cloud at random.
      description: "[Sample Photo Download Link](https://raw.githubusercontent.com/amueller/word_cloud/master/examples/alice_color.png)\n[Sample Text Download Link](https://raw.githubusercontent.com/amueller/word_cloud/master/examples/alice.txt)"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                lang:
                  type: string
                  example: en_ewt_0.2.0
                image:
                  type: string
                  format: binary
                text:
                  type: string
                  format: binary
      responses:
        '200':
          description: Result image.
          content:
            image/*:
              schema:
                type: string
                format: binary
        '400':
          description: Bad request
  
tags:
  - name: Word Cloud
    description: Generate word-cloud from image and text.
servers:
  - url: 'https://master-word-cloud-gkswjdzz.endpoint.ainize.ai'

security: [] 